before_script:
  - sh -c 'bundle install && bundle exec rake db:create db:migrate'
after_success:
  - gem install rhc
  - git remote add openshift ${OPENSHIFT_REPOSITORY}
  - echo 'Host karotzci-koboyz.rhcloud.com' >> ~/.ssh/config
  - echo '   StrictHostKeyChecking no' >> ~/.ssh/config
  - echo '   CheckHostIP no' >> ~/.ssh/config
  - echo '   UserKnownHostsFile=/dev/null' >> ~/.ssh/config
  - ssh-keygen -t rsa -f ~/.ssh/travis -N ''
  - rhc sshkey-add travis ~/.ssh/travis.pub -l "${OPENSHIFT_USER}" -p "${OPENSHIFT_PASSWORD}"
  - git push openshift master
  - rhc sshkey-remove travis -l "${OPENSHIFT_USER}" -p "${OPENSHIFT_PASSWORD}"
env:
  global:
    - DB=mysql
    - secure: "clGb47bKcIUbCHn5oajm8zv8JF9uB1dghdmm9/yxsV+RzWwOTk7gcvESJuxnAKeNawnaP+expcq6RKG4PBNZzLdJVjbZqjPcVjvwknsiYaVKYZHRg0tqcXYoISoHk7t+zJ5OldfDq9NXevqMPSFYVdCg9whWKjQfnFbxizax67I="
    - secure: "cHK+F9dn92vX7Yl/aILWEvxmLUsUkkut3xsz/iawjfEYRpTnEuh4kc6OhSHvzxzk7+NjJmmwc6EfFJAHzdYTN+3c8wW3AINCTfvfB9A2UYkC54NzUKOmUe+rbMMIxDTVmE709DnFAkO58S/bE0sSDO/NHtm/aLVJtn+CLBGt0to="
    - secure: "gqiZNyoRN994VnkWiue+D8GCzWEKUzPr+B8oU6GPbaj0/sIfGhBGm8fkTXD5lZU2xSYxMkkr8saxT5xfPw1KdHvbnBRlIh0bwza0iA5oPEK3KOGn1aAO0fmPAHC1mMxlwkRQE5VYr1YJOnFc1eThrXrGq0opUomc1KcorohKl54="
git:
  submodules: false
language: ruby
rvm:
- 1.9.3
script: bundle exec rspec spec
