before_script:
  - cp config/database-ci.yml config/database.yml
  - psql -c 'create database karotzci_test;' -U postgres
  - sh -c 'bundle install && bundle exec rake db:create db:migrate'
after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:${HEROKU_APP}.git
  - echo 'Host heroku.com' >> ~/.ssh/config
  - echo '   StrictHostKeyChecking no' >> ~/.ssh/config
  - echo '   CheckHostIP no' >> ~/.ssh/config
  - echo '   UserKnownHostsFile=/dev/null' >> ~/.ssh/config
  - ssh-keygen -t rsa -C 'deploy@travis-ci.org' -f ~/.ssh/travis -N ''
  - heroku keys:add ~/.ssh/travis.pub
  - yes | git push heroku master
  - if git log ${TRAVIS_COMMIT_RANGE} | grep -E '\[migrations\]'; then heroku run rake db:migrate --app ${HEROKU_APP}; fi
  - heroku keys:remove deploy@travis-ci.org
env:
  global:
    - secure: "DIPgDy3G3uR/4fye/47W7BsCfJ9KkEMyTxrfnPaLn73zBnjwP1UQ3bwZuOabfnPTF7Y1ctM4LsKcAAkm64WrZxEQZqhkcfyZ4Z5FV4RBYa3Lw6XGHGKeJq5qeg1oxAtFv8LUq7eguGsnVXmeWRyVIyN/hfih9Fc1nYmFYCts2qI="
    - secure: "a3CG4O5CrwL68xPhkGSvhe2j/KKen3eqnzVs4jEGnSZ0PKHtrhGQ19WU6zaHyaEQCVf7ABJOdDYwH5I7PWt5pB2mHylxcwiN+odq1FkU65ImpcGTSCR0k0XyndtPLVOIqqMoSIcfEYjDnUHf7bmNul+C8PlV7kpD2mGpw/wWxww="
    - DB=postgresql
git:
  submodules: false
language: ruby
rvm:
  - 2.0.0
script: bundle exec rspec spec
