development:
  adapter:  mysql2
  database: karotz-ci_development
  user:     root
  pool:     5
  timeout:  5000

production:
  adapter:  mysql2
  encoding: utf8
  database: <%= ENV['OPENSHIFT_APP_NAME'] %>
  pool:     5
  host:     <%= ENV['OPENSHIFT_MYSQL_DB_HOST'] %>
  port:     <%= ENV['OPENSHIFT_MYSQL_DB_PORT'] %>
  username: <%= ENV['OPENSHIFT_MYSQL_DB_USERNAME'] %>
  password: <%= ENV['OPENSHIFT_MYSQL_DB_PASSWORD'] %>
  socket:   <%=ENV['OPENSHIFT_MYSQL_DB_SOCKET'] %>
